displayName: OWASP CRS Modsecurity Plugin
type: middleware

import: github.com/kenshaw/traefik-modsec

summary: "Traefik plugin to proxy requests through owasp/modsecurity-crs"

testData: {}

iconPath: ./img/icon.png
bannerPath: ./img/banner.png
